const fs = require('fs');

try {
    let content = fs.readFileSync('index.html', 'utf8');

    // MAPPING OLD SECTIONS TO REMOVE
    const homeStart = content.indexOf('<section id="content-home"');
    const processStart = content.indexOf('<section id="content-process"');
    const encStart = content.indexOf('<section id="content-encyclopedia"');

    if (homeStart === -1 || processStart === -1 || encStart === -1) {
        throw new Error("Could not find section boundaries");
    }

    const processEndMatch = content.lastIndexOf('</section>', encStart);
    if (processEndMatch === -1) throw new Error("Could not find process end");
    const processEnd = processEndMatch + 10; // length of </section>

    const beforeContent = content.substring(0, homeStart);
    const afterContent = content.substring(processEnd);

    // NEW CONTENT HTML
    const newHomeContent = `
    <section id="content-home" class="animate-fade-in w-full">
        <!-- Hero -->
        <div class="relative h-screen max-h-[900px] w-full overflow-hidden">
            <img src="assets/hero.jpg" class="absolute inset-0 w-full h-full object-cover">
            <div class="absolute inset-0 bg-black/40 flex flex-col items-center justify-center text-center p-6">
                <h1 class="text-5xl md:text-8xl font-bold text-white mb-6 tracking-tighter drop-shadow-2xl" style="font-family: 'TheJamsil';">JUNGLE WAVE</h1>
                <p class="text-xl md:text-2xl text-gray-200 font-light tracking-[0.1em] mb-12 drop-shadow-lg" style="font-family: 'TheJamsil'; word-break: keep-all;">자연의 생명력을 일상으로 가져오는 바이오필릭 디자인 스튜디오</p>
                <button onclick="switchTab('process')" class="bg-white/10 hover:bg-white text-white hover:text-black border border-white/50 backdrop-blur-md px-12 py-4 font-bold tracking-[0.2em] uppercase transition-all duration-300">
                    Explore
                </button>
            </div>
        </div>

        <!-- Featured Works (Deep Dive Project Gallery) -->
        <div class="max-w-7xl mx-auto px-6 py-24 bg-white dark:bg-black">
            <div class="text-center mb-16">
                <h2 class="text-3xl font-bold text-black dark:text-white uppercase tracking-tight mb-2" style="font-family: 'TheJamsil';">Deep Dive Projects</h2>
                <div class="w-12 h-1 bg-black dark:bg-white mx-auto"></div>
            </div>
            
            <div id="portfolioGrid" class="grid grid-cols-1 md:grid-cols-3 gap-1">
                <!-- Generated by JS -->
            </div>
        </div>
    </section>
    `;

    const newProcessContent = `
    <section id="content-process" class="hidden animate-fade-in w-full max-w-7xl mx-auto px-6 py-20">
        <div class="text-center mb-24">
            <h2 class="text-5xl font-bold text-black dark:text-white uppercase tracking-tighter mb-6" style="font-family: 'TheJamsil';">The Process</h2>
            <p class="text-gray-400 max-w-xl mx-auto tracking-wide">JUNGLE WAVE VIVARIUM SYSTEM</p>
        </div>

        <div class="space-y-32">
            <!-- Step 1 -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                <div class="h-[600px] bg-gray-100 dark:bg-zinc-900 overflow-hidden relative group">
                    <img src="assets/process1.jpg" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105">
                </div>
                <div>
                    <span class="text-xs font-bold text-jungle-600 dark:text-jungle-400 uppercase tracking-widest mb-2 block">Step 01</span>
                    <h3 class="text-4xl font-bold text-black dark:text-white mb-6" style="font-family: 'TheJamsil'; word-break: keep-all;">상담 및 생물 선정</h3>
                    <p class="text-gray-600 dark:text-gray-400 leading-relaxed text-lg" style="word-break: keep-all;">
                        사육 환경과 사용자의 니즈를 분석하여 가장 적합한 생물과 컨셉을 제안합니다.
                    </p>
                </div>
            </div>

            <!-- Step 2 -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center flex-row-reverse">
                <div class="order-2 md:order-1">
                    <span class="text-xs font-bold text-jungle-600 dark:text-jungle-400 uppercase tracking-widest mb-2 block">Step 02</span>
                    <h3 class="text-4xl font-bold text-black dark:text-white mb-6" style="font-family: 'TheJamsil'; word-break: keep-all;">레이아웃 설계</h3>
                    <p class="text-gray-600 dark:text-gray-400 leading-relaxed text-lg" style="word-break: keep-all;">
                        프리미엄 유목과 수석을 활용해 생태계의 뼈대가 되는 구조를 정교하게 디자인합니다.
                    </p>
                </div>
                 <div class="h-[600px] bg-gray-100 dark:bg-zinc-900 overflow-hidden relative group order-1 md:order-2">
                    <img src="assets/process2.jpg" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105">
                </div>
            </div>

            <!-- Step 3 -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
                <div class="h-[600px] bg-gray-100 dark:bg-zinc-900 overflow-hidden relative group">
                    <img src="assets/process3.jpg" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105">
                </div>
                <div>
                    <span class="text-xs font-bold text-jungle-600 dark:text-jungle-400 uppercase tracking-widest mb-2 block">Step 03</span>
                    <h3 class="text-4xl font-bold text-black dark:text-white mb-6" style="font-family: 'TheJamsil'; word-break: keep-all;">식재 및 식생 안착</h3>
                    <p class="text-gray-600 dark:text-gray-400 leading-relaxed text-lg" style="word-break: keep-all;">
                        적합한 식물을 식재하고 습도 순환 시스템을 구축하여 비바리움이 스스로 숨 쉬게 합니다.
                    </p>
                </div>
            </div>

            <!-- Step 4 -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-16 items-center flex-row-reverse">
                <div class="order-2 md:order-1">
                    <span class="text-xs font-bold text-jungle-600 dark:text-jungle-400 uppercase tracking-widest mb-2 block">Step 04</span>
                    <h3 class="text-4xl font-bold text-black dark:text-white mb-6" style="font-family: 'TheJamsil'; word-break: keep-all;">안전 배송 및 관리</h3>
                    <p class="text-gray-600 dark:text-gray-400 leading-relaxed text-lg" style="word-break: keep-all;">
                        완성된 작은 생태계를 공간에 안전하게 전달하고, 지속 가능한 관리 가이드를 제공합니다.
                    </p>
                </div>
                 <div class="h-[600px] bg-gray-100 dark:bg-zinc-900 overflow-hidden relative group order-1 md:order-2">
                    <img src="assets/process4.jpg" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105">
                </div>
            </div>
        </div>
    </section>
    `;

    // Reconstruct core HTML
    content = beforeContent + newHomeContent + "\n" + newProcessContent + "\n" + afterContent;

    // MODAL HTML to append before </body>
    const modalHTML = `
    <!-- Portfolio Modal -->
    <div id="portfolioModal" class="fixed inset-0 z-[100] hidden items-center justify-center p-4">
        <div class="absolute inset-0 bg-black/90 backdrop-blur-sm transition-opacity" onclick="closePortfolio()"></div>
        <div class="relative w-full max-w-6xl bg-white dark:bg-black rounded-none shadow-2xl overflow-hidden transform scale-95 opacity-0 transition-all duration-300 flex flex-col md:flex-row h-[85vh] md:h-[700px] border border-gray-200 dark:border-zinc-800" id="portfolioModalContent">
            
            <button onclick="closePortfolio()" class="absolute top-4 right-4 z-50 text-white md:text-black dark:text-white bg-black/50 md:bg-white/50 dark:bg-black/50 hover:bg-black md:hover:bg-white dark:hover:bg-black p-2 rounded-full transition-colors backdrop-blur-md">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg>
            </button>

            <!-- Image slider area -->
            <div class="relative w-full md:w-2/3 h-1/2 md:h-full bg-black group overflow-hidden">
                <img id="modalMainImg" src="" class="w-full h-full object-cover transition-opacity duration-300">
                
                <button onclick="prevSlide()" class="absolute left-4 top-1/2 -translate-y-1/2 text-white bg-black/50 hover:bg-black p-3 rounded-full opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-md">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" /></svg>
                </button>
                <button onclick="nextSlide()" class="absolute right-4 top-1/2 -translate-y-1/2 text-white bg-black/50 hover:bg-black p-3 rounded-full opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-md">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" /></svg>
                </button>

                <div class="absolute bottom-6 left-0 right-0 flex justify-center gap-3 z-20" id="modalDots">
                </div>
                <!-- Gradient to make dots visible -->
                <div class="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-black/80 to-transparent pointer-events-none"></div>
            </div>

            <!-- Detail info area -->
            <div class="w-full md:w-1/3 p-10 flex flex-col bg-white dark:bg-black overflow-y-auto border-l border-gray-100 dark:border-zinc-800">
                <h3 id="modalTitle" class="text-3xl font-bold mb-6 text-black dark:text-white leading-tight" style="font-family: 'TheJamsil';">Title</h3>
                <div class="w-10 h-1 bg-jungle-500 mb-8"></div>
                <p id="modalDesc" class="text-gray-600 dark:text-gray-400 leading-loose text-sm md:text-base flex-grow" style="word-break: keep-all;">
                    Description
                </p>
                <div class="mt-10 pt-8 border-t border-gray-100 dark:border-zinc-800">
                    <button onclick="window.open('https://talk.naver.com/', '_blank')" class="w-full py-4 bg-black text-white dark:bg-white dark:text-black font-bold tracking-widest uppercase hover:bg-jungle-600 dark:hover:bg-jungle-500 transition-colors text-sm">
                        Consultation
                    </button>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        const portfolioData = [
            {
                id: 'p1',
                title: 'DEEP FOREST : CRESTED GECKO',
                mainImg: 'assets/hero.jpg',
                images: ['assets/hero.jpg', 'assets/process1.jpg', 'assets/process2.jpg'],
                desc: '자연의 웅장함을 유리관 안에 그대로 옮겨 놓은 바이오필릭 디자인 생태계입니다. 크레스티드 게코가 서식하는 환경을 고려하여 프리미엄 유목과 수석으로 입체적인 활동 공간을 구성하였습니다. 내부 습도는 식물의 자연스러운 증산 작용을 통해 안정적으로 유지되며, 공기의 흐름까지 계산된 디자인으로 시간이 지날수록 완성도가 높아집니다.'
            },
            {
                id: 'p2',
                title: 'LIVING ART : TROPICAL VIBE',
                mainImg: 'assets/process2.jpg',
                images: ['assets/process2.jpg', 'assets/process3.jpg', 'assets/process4.jpg'],
                desc: '정글 특유의 몽환적인 분위기를 극대화한 작품으로, 다양한 무드 연출이 가능합니다. 다채로운 열대 식생이 어우러져 공간의 분위기를 변모시키는 확실한 인테리어 오브제 역할을 수행합니다. 생물의 안전과 식물의 생장을 모두 충족하는 환경 제어 시스템이 적용되었습니다.'
            },
            {
                id: 'p3',
                title: 'AQUA NATURE : HYBRID SYSTEM',
                mainImg: 'assets/process4.jpg',
                images: ['assets/process4.jpg', 'assets/hero.jpg', 'assets/process1.jpg'],
                desc: '수공간과 육공간이 조화롭게 결합된 고난이도의 팔루다리움 구조입니다. 떨어지는 물소리와 함께 식생의 향기를 공간에 퍼뜨리며 강력한 스트레스 완화 효과를 선사합니다. 정글웨이브만의 특별한 구조 설계로 관리의 편의성까지 확보한 독보적인 에코 빌드입니다.'
            }
        ];

        let currentSlideIndex = 0;
        let currentProjectImages = [];

        function initPortfolio() {
            const grid = document.getElementById('portfolioGrid');
            if(!grid) return;
            grid.innerHTML = '';
            portfolioData.forEach(p => {
                grid.innerHTML += \`
                    <div class="aspect-square bg-gray-100 dark:bg-zinc-900 overflow-hidden group relative cursor-pointer" onclick="openPortfolio('\${p.id}')">
                        <img src="\${p.mainImg}" class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110 grayscale hover:grayscale-0">
                        <div class="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                            <span class="text-white font-bold tracking-[0.2em] uppercase">\${p.title.split(' : ')[0]}</span>
                        </div>
                    </div>
                \`;
            });
        }

        function openPortfolio(id) {
            const project = portfolioData.find(p => p.id === id);
            if(!project) return;
            
            currentProjectImages = project.images;
            currentSlideIndex = 0;
            
            document.getElementById('modalTitle').innerText = project.title;
            document.getElementById('modalDesc').innerText = project.desc;
            
            renderSlide();
            
            const modal = document.getElementById('portfolioModal');
            const content = document.getElementById('portfolioModalContent');
            
            modal.classList.remove('hidden');
            modal.classList.add('flex');
            
            // Trigger animation
            setTimeout(() => {
                content.classList.remove('scale-95', 'opacity-0');
                content.classList.add('scale-100', 'opacity-100');
            }, 10);
            
            document.body.style.overflow = 'hidden'; 
        }

        function closePortfolio() {
            const modal = document.getElementById('portfolioModal');
            const content = document.getElementById('portfolioModalContent');
            
            content.classList.remove('scale-100', 'opacity-100');
            content.classList.add('scale-95', 'opacity-0');
            
            setTimeout(() => {
                modal.classList.add('hidden');
                modal.classList.remove('flex');
                document.body.style.overflow = 'auto';
            }, 300);
        }

        function renderSlide() {
            const mainImg = document.getElementById('modalMainImg');
            mainImg.style.opacity = '0';
            
            setTimeout(() => {
                mainImg.src = currentProjectImages[currentSlideIndex];
                mainImg.style.opacity = '1';
            }, 150);
            
            const dotsContainer = document.getElementById('modalDots');
            dotsContainer.innerHTML = '';
            currentProjectImages.forEach((_, idx) => {
                const dot = document.createElement('button');
                dot.className = \`w-2 h-2 rounded-full transition-all duration-300 \${idx === currentSlideIndex ? 'bg-white scale-125 w-4' : 'bg-white/50 hover:bg-white/80'}\`;
                dot.onclick = () => {
                    currentSlideIndex = idx;
                    renderSlide();
                };
                dotsContainer.appendChild(dot);
            });
        }

        function prevSlide() {
            currentSlideIndex = (currentSlideIndex - 1 + currentProjectImages.length) % currentProjectImages.length;
            renderSlide();
        }

        function nextSlide() {
            currentSlideIndex = (currentSlideIndex + 1) % currentProjectImages.length;
            renderSlide();
        }

        // Initialize on load
        setTimeout(initPortfolio, 500);
    </script>
    `;

    if (!content.includes('id="portfolioModal"')) {
        content = content.replace('</body>', modalHTML + '\n</body>');
    }

    fs.writeFileSync('index.html', content, 'utf8');
    console.log('Portfolio update successful.');
} catch (err) {
    console.error('Error:', err);
    process.exit(1);
}
