const fs = require('fs');
const path = require('path');

const assetDir = path.join(__dirname, 'assets');

// Map old names to new names
const mapping = [
    { old: '250409 정글웨이브110877(조절).jpg', new: 'hero.jpg' },
    { old: '[꾸미기]250409 정글웨이브110916.jpg', new: 'process1.jpg' },
    { old: '[꾸미기]250409 정글웨이브110919.jpg', new: 'process2.jpg' },
    { old: '[꾸미기]250409 정글웨이브110923.jpg', new: 'process3.jpg' },
    { old: '20241111_183148.jpg', new: 'process4.jpg' }
];

try {
    // 1. Rename Files
    mapping.forEach(m => {
        const oldPath = path.join(assetDir, m.old);
        const newPath = path.join(assetDir, m.new);
        if (fs.existsSync(oldPath)) {
            fs.renameSync(oldPath, newPath);
            console.log(`Renamed: ${m.old} -> ${m.new}`);
        } else {
            console.log(`Skipped (Not Found): ${m.old}`);
        }
    });

    // 2. Update HTML References
    let content = fs.readFileSync('index.html', 'utf8');

    // We search for the ENCODED version that apply_images.js inserted.
    // e.g. "assets/250409%20%EC%A0%95..."
    // Since we can't easily guess the exact encoding string used previously (different environments behave differently),
    // We will search for the *Folder Prefix* "assets/" and regex match the rest?
    // Or just search for the encoded strings generated by JS?

    // Actually, apply_images.js used `encodeURIComponent` on each segment.
    // So "250409 정글웨이브..." -> "250409%20%EC%A0%95%EA%B8%80%EC%9B%A8%EC%9D%B4%EB%B8%8C..."
    // Instead of guessing, let's use Regex to find `src="assets/..."` and replace based on context?
    // The context is tricky.

    // Easier way: The previous `apply_images.js` used `t.new` as the key for replacement.
    // We can re-run the same `encodeURIComponent` logic to find the string to replace!

    mapping.forEach(m => {
        // Generate the EXACT string currently in HTML
        const encodedOldName = m.old.split('/').map(s => encodeURIComponent(s)).join('/');
        // Note: m.old here is just filename. split('/') has 1 element.
        // But `apply_images.js` prepended "assets/".
        // So the string in HTML is likely `assets/` + encodedFilename.

        const searchStr = `assets/${encodeURIComponent(m.old)}`;
        const contentStr = `assets/${m.new}`; // Simple English, no encoding needed

        // Global replace
        content = content.split(searchStr).join(contentStr);
    });

    fs.writeFileSync('index.html', content, 'utf8');
    console.log('HTML links updated to clean filenames.');

} catch (err) {
    console.error('Error:', err);
    process.exit(1);
}
